language: java

jdk:
    - oraclejdk8

install:
    - ./gradlew shadowJar

script:
    - java -jar ./build/libs/ReadTools.jar --version
    - ./gradlew jacocoTestReport

after_success:
    - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy
    - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
