codecov:
  branch: master

coverage:
  precision: 3
  round: nearest
  range: "50...100"

  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 1%

comment:
  layout: "header, diff, changes, uncovered, tree"
behavior: new